site_name: Ontology
site_url: https://chinchalinchin.github.io/ontology/
repo_url: https://github.com/chinchalinchin/ontology
repo_name: chinchalinchin/ontology

theme:
  name: material
  palette: 
    scheme: slate
    primary: red
    accent: deep orange
  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes

nav:
  - Home: index.md
  - Overview: 00-overview.md
  - Assets: 01-assets.md
  - Schema: 03-schema.md
  - Interface: 03-api.md
  - Pseudocode: 03-pseudocode.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

exclude:
  - '**/notes.md'
  
extra_javascript:
  - .static/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google