site_name: Ontology
site_url: https://chinchalinchin.github.io/ontology/
repo_url: https://github.com/chinchalinchin/ontology
repo_name: chinchalinchin/ontology

theme:
  name: material
  palette: 
    scheme: slate
    primary: deep purple
    accent: blue
  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes

nav:
  - Index: index.md
  - Overview: 00-overview.md
  - Assets: 01-assets.md
  - Sprites: 02-sprites.md
  - Compositions: 03-compositions.md
  - Intentions: 04-intentions.md
  - Mechanics: 05-mechanics.md
  - Widgets: 06-widgets.md
  - Sounds: 07-sounds.md
  - Plots: 08-plots.md
  - Emergence: 09-emergence.md
  - Architecture: 10-architecture.md
  - Appendix: 
    - Index: appendices/index.md
    - References: appendices/00-references.md
    - Schemas: appendices/01-schemas.md
  - Reports:
    - Unit Test Coverage: coverage/index
markdown_extensions:
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: docs

exclude:
  - '**/.board/*.md'
  - '**/.assets/**'
  - '**/.*.md'
exclude_docs: |
  .board/*.md
  .assets/**
  .*.md
extra_javascript:
  - static/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google