[pytest]
pythonpath = 
    src
    .
markers =
    # ---------------------- WORKFLOW TAGS
    combat: Combat Workflow unit tests
    fluids: Fluid Workflow unit tests
    intentions: Intention Workflow unit tests
    menus: Menu Workflow unit tests
    motion: Motion Worfklow unit tests
    pathfinding: Pathfinding Workflow unit tests
    player: Player Workflow unit tests
    plots: Plot Workflow unit tests
    # ---------------------- PACKAGE TAGS
    services: Application Service unit tests