[pytest]
pythonpath = 
    src
    .
markers =
    # ---------------------- WORKFLOW TAGS
    combat: Combat Workflow unit tests
    compositions: Composition Worfklow unit tests
    fluids: Fluid Workflow unit tests
    geology: Geology Workflow unit tests 
    intentions: Intention Workflow unit tests
    main: Main Workflow unit tests
    menus: Menu Workflow unit tests
    motion: Motion Workflow unit tests
    orchestration: Orchestration Worfklow unit tests
    pathfinding: Pathfinding Workflow unit tests
    physics: Physics Worfklow unit tests
    player: Player Workflow unit tests
    plots: Plot Workflow unit tests
    seasons: Seasons Workflow unit tests
    # ---------------------- COMPONENT TAGS
    services: Application Service unit tests
    animations: Application Asset Animation unit tests
    franes: Application Asset Frame unit tests