[pytest]
pythonpath = 
    src
    .
markers =
    fluids: Fluid Workflow unit test
    intentions: Intention Workflow unit tests
    motion: Motion Worfklow unit tests
    pathfinding: Pathfinding Workflow unit tests