stateDiagram-v2
    direction LR

    attack --> attack
    attack --> hunt
    attack --> scavenge

    barter --> threaten
    barter --> idle

    build --> idle

    escape --> escape
    escape --> return

    find --> interact
    find --> speak

    follow --> follow
    follow --> speak
    follow --> idle

    hunt --> attack
    hunt --> idle

    idle --> wander
    idle --> find
    idle --> idle

    interact --> idle

    mine --> build
    mine --> mine
    mine --> idle

    mock --> threaten
    mock --> idle

    return --> idle

    scavenge --> idle

    speak --> follow
    speak --> idle

    sprint --> idle

    threaten --> attack
    threaten --> hunt
    threaten --> idle

    wander --> idle