stateDiagram-v2
    sapling --> bush
    bush --> branch
    branch --> adult
    adult --> healthy
    adult --> vibrant
    adult --> abscise
    adult --> snowcapt
    adult --> dying
    vibrant --> healthy
    vibrant --> dying
    healthy --> abscise
    healthy --> dying
    abscise --> snowcapt
    abscise --> dying
    snowcapt --> vibrant
    snowcapt --> dying
    dying --> vibrant
    dying --> healthy
    dying --> dead
    dead --> stump
    stump --> sapling