stateDiagram-v2
    direction LR

    attack --> attack
    attack --> hunt
    attack --> scavenge

    attract --> barter
    attract --> speak

    barter --> threaten
    barter --> idle

    build --> idle

    escape --> escape
    escape --> return

    find --> scavenge
    find --> interact
    find --> speak
    find --> return

    follow --> follow
    follow --> speak
    follow --> wander

    hunt --> attack
    hunt --> return

    idle --> wander
    idle --> idle

    interact --> idle

    mine --> build
    mine --> mine
    mine --> idle

    mock --> threaten
    mock --> idle

    return --> idle
    return --> return

    scavenge --> idle

    speak --> follow
    speak --> idle

    sprint --> return
    sprint --> idle

    threaten --> attack
    threaten --> hunt
    threaten --> idle

    wander --> idle