#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR=$SCRIPT_DIR/..
BUILD_DIR=$PROJECT_DIR/dist
SRC_DIR=$PROJECT_DIR/src
VENV_DIR=$PROJECT_DIR/.venv/bin

source $VENV_DIR/activate

cynthonize $SRC_DIR/onta/engine/static/*.pyx