#!/bin/bash

apt update -y

# Python Image Library (PIL/Pillow)
apt install -y libjpeg-dev \
                zlib1g \
                libtiff-dev \
                libfreetype6-dev \
                liblcms2-utils \
                libwebp-dev \
                libpng-dev \
                libz-dev \
                tcl-dev \
                libraqm-dev \
                libxcb-util-dev

# PySide6