#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_DIR=$SCRIPT_DIR/..
BUILD_DIR=$PROJECT_DIR/dist
SRC_DIR=$PROJECT_DIR/src
VENV_DIR=$PROJECT_DIR/.venv/bin

VERSION="$(cat $SRC_DIR/version.txt)"

cd $PROJECT_DIR

if [ -d $BUILD_DIR ]
then
    rm -r $BUILD_DIR
fi
if [ -d $SRC_DIC/ontology.egg-info ]
then
    rm -r $SRC_DIR/ontology.egg-info
fi

cythonize -i $SRC_DIR/onta/engine/static/*.pyx

python3 -m build

cd $BUILD_DIR

pip3 install "ontology-$VERSION-py3-none-any.whl" --force-reinstall
# pip3 install "ontology-$VERSION-cp38-cp38-linux_x86_64.whl" --force-reinstall