# ----------------------------------------------------
properties:
  paths:
    root: <root-path>
    actions: .githubs/workflows/
    blocks: .prompts/tasks/.blocks/
    board: .prompts/board/
    phases: .prompts/board/phases/
    docs: docs/
    tests: tests/unit/
    fixtures: tests/unit/fixtures/
  project:
    title: ontology
  user:
    username: <username>
    ssh: <keypath>
    hostname: <hostname>
  urls: 
    github: github.com/chinchalinchin
# ----------------------------------------------------
task:
# ----------------------------------------------------
  template: <path>/<file>.md.j2
# ----------------------------------------------------
  parameters:
    diagram: <diagram>.mmd
    workflow: <workflow>
# ----------------------------------------------------
tools:
# ----------------------------------------------------
  views:
    manager:
      board: false
      specs: false
      docs: false
    source:
      workflow: false
    shell:
      directory: false
      commands: false
    tests:  
      console: false
      fixtures: false
      workflow: false
# ----------------------------------------------------
  parameters:
    manager:
      board:
        phase: <board-phase>
        action: <board-action>
      docs:
        exclude:
          - <doc-page>.md
      specs:
        - <spec-page>.md
    source:
      workflow: <workflow>
    shell:
      directory: tree -L 3 --gitignore -I "build|*.so|*.png|__pycache__|__init__.py"
      commands: []
    tests:
      console:
        pytest: pytest -m <workflow>
      fixtures:
        - <fixture>
      workflow: <workflow>