name: ontology-docs

on:
  workflow_run:
    workflows: ["ontology-tests"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    name: ontology-docs
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: chinchalinchin/ontology-builder:latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup
        run: |
          uv venv --python 3.14
          uv pip install --group docs --group analysis
      
      - name: download-coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: docs/coverage
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: dependency-trees
        run: | 
          chmod +x scripts/dependencies/main.sh
          uv run ./scripts/dependencies/main.sh

      - name: documentation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global --add safe.directory /__w/ontology/ontology
          mkdocs gh-deploy --force